### PR TITLE
add AbstractReal

### LINKED ISSUE #20: Add `AbstractReal`
Yeah, this is awful. But this PR may never be merged: https://github.com/JuliaStats/Distributions.jl/pull/1691 and other `<: Real` limitations exist in the ecosystem. Adding `AbstractReal` here would be basically identical code to `AbstractNumber`, but `<: Real`, and can share most of the code.

### PR DESCRIPTION
**Pull request by rafaqz**
Closes #20 

The ambiguities on `Real` are pretty painful, and there seem to be some new ones on `Number`

Maybe better to give up on anything like this working at all...

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I've given up on it, to be honest 😅

**Comment by rafaqz** [comment]
Yeah, this is totally just for ModelParameters.jl parameters to work in more places like Distributions.jl. 

The number system could have been better designed... I feel like whatever trash we have here is evidence for the case come 2.0 😂

**Comment by rafaqz** [comment]
Codecov is borked

Otherwise this is good to merge

**Comment by SimonDanisch** [comment]
I guess you should have all rights to merge & tag this, right?

**Review by SimonDanisch — APPROVED** [review]

**Comment by rafaqz** [comment]
Yeah will do

**Comment by rafaqz** [comment]
Actually it wants signed commits now? Could you relax that a little in the settings?

**Comment by SimonDanisch** [comment]
Done

**Pull request merged**
